# Generated by Django 3.1.7 on 2021-04-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psyco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='news_photo')),
            ],
        ),
        migrations.CreateModel(
            name='horoscope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('source', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='news_photo')),
            ],
        ),
    ]
