# Generated by Django 3.1.7 on 2021-04-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psyco', '0005_auto_20210410_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='advice',
            new_name='advice_model',
        ),
        migrations.RenameModel(
            old_name='news',
            new_name='news_model',
        ),
    ]
