# Generated by Django 3.1.7 on 2021-04-17 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psyco', '0006_auto_20210410_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_model',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 17)),
        ),
    ]
