# Generated by Django 3.1.7 on 2021-04-17 21:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psyco', '0008_message_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 18, 0, 41, 53, 51357)),
        ),
        migrations.AlterField(
            model_name='news_model',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 18)),
        ),
        migrations.CreateModel(
            name='first_message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 4, 18, 0, 41, 53, 52356))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
