# Generated by Django 3.1.7 on 2021-04-17 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psyco', '0009_auto_20210418_0041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='first_message',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
