# Generated by Django 3.1.7 on 2021-04-19 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psyco', '0010_auto_20210418_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_model',
            name='date',
            field=models.DateField(default=datetime.date(2021, 4, 19)),
        ),
    ]
