# Generated by Django 3.1.7 on 2021-04-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psyco', '0013_auto_20210420_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
