# Generated by Django 3.1.7 on 2021-04-20 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psyco', '0014_auto_20210420_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RoomSpecialist', to=settings.AUTH_USER_MODEL, verbose_name='Specialist')),
                ('Student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RoomStudent', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
        ),
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner', models.CharField(max_length=2)),
                ('MessageDialog', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Message date')),
                ('RoomDialog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='psyco.room', verbose_name='Room_dialog')),
            ],
        ),
    ]
